apiVersion: kubeflow.org/v1
kind: TFJob
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"kubeflow.org/v1","kind":"TFJob","metadata":{"annotations":{},"name":"tfjob-smoketest","namespace":"default"},"spec":{"Run
Policy":{"SchedulingPolicy":{"MinAvailable":2,"Queue":"redbook-queue"}},"cleanPodPolicy":"Running","tfReplicaSpecs":{"Worker":{"replicas":4,"r
estartPolicy":"OnFailure","template":{"spec":{"containers":[{"command":["sh","-c","tail -f /dev/null"],"env":[{"name":"workers","value":"4"},{
"name":"DLC_PLATFORM","value":"Aliyun"},{"name":"LICENSE_SDK_HOST","value":"http://license-pai.cn-shanghai.data.aliyun.com"}],"image":"registr
y-vpc.cn-shanghai.aliyuncs.com/pai-dlc/tensorflow-training:1.15-cpu-py36-ubuntu18.04","imagePullPolicy":"Always","name":"tensorflow","ports":[
{"containerPort":20000,"name":"tfjob-port"}],"workingDir":"/workspace"}],"hostIPC":true,"hostPID":true}}}}}}
  creationTimestamp: "2021-06-16T08:13:57Z"
  generation: 1
  managedFields:
  - apiVersion: kubeflow.org/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:kubectl.kubernetes.io/last-applied-configuration: {}
      f:spec:
        .: {}
        f:cleanPodPolicy: {}
        f:tfReplicaSpecs:
          .: {}
          f:Worker:
            .: {}
            f:replicas: {}
            f:restartPolicy: {}
            f:template:
              .: {}
              f:spec:
                .: {}
                f:hostIPC: {}
                f:hostPID: {}
    manager: kubectl
    operation: Update
    time: "2021-06-16T08:13:57Z"
  - apiVersion: kubeflow.org/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:spec:
        f:tfReplicaSpecs:
          f:Worker:
            f:template:
              f:metadata:
                .: {}
                f:creationTimestamp: {}
              f:spec:
                f:containers: {}
      f:status:
        .: {}
        f:conditions: {}
        f:replicaStatuses:
          .: {}
          f:Worker: {}
        f:startTime: {}
    manager: tf-operator.v1
    operation: Update
    time: "2021-06-16T08:13:58Z"
  name: tfjob-smoketest
  namespace: default
  resourceVersion: "682906623"
  selfLink: /apis/kubeflow.org/v1/namespaces/default/tfjobs/tfjob-smoketest
  uid: ce19d2ec-ee0d-420a-b53a-fc26dac48325
spec:
  RunPolicy:
    SchedulingPolicy:
      MinAvailable: 2
      Queue: redbook-queue
  cleanPodPolicy: Running
  tfReplicaSpecs:
    Worker:
      replicas: 4
      restartPolicy: OnFailure
      template:
        spec:
          containers:
          - command:
            - sh
            - -c
            - tail -f /dev/null
            env:
            - name: workers
              value: "4"
            - name: DLC_PLATFORM
              value: Aliyun
            - name: LICENSE_SDK_HOST
              value: http://license-pai.cn-shanghai.data.aliyun.com
            image: registry-vpc.cn-shanghai.aliyuncs.com/pai-dlc/tensorflow-training:1.15-cpu-py36-ubuntu18.04
            imagePullPolicy: Always
            name: tensorflow
            ports:
            - containerPort: 20000
              name: tfjob-port
            workingDir: /workspace
          hostIPC: true
          hostPID: true
status:
  conditions:
  - lastTransitionTime: "2021-06-16T08:13:57Z"
    lastUpdateTime: "2021-06-16T08:13:57Z"
    message: TFJob tfjob-smoketest is created.
    reason: TFJobCreated
    status: "True"
    type: Created
  replicaStatuses:
    Worker: {}
  startTime: "2021-06-16T08:13:57Z"
